export const GET_ERRORS ="GET_ERRORS";
export const GET_QYTETETS ="GET_QYTETETS";
export const GET_QYTETI="GET_QYTETI";
export const CREATE_QYTETI="CREATE_QYTETI";
export const DELETE_QYTETI="DELETE_QYTETI";

export const GET_SPITALIS ="GET_SPITALIS";
export const GET_SPITALI="GET_SPITALI";
export const CREATE_SPITALI="CREATE_SPITALI";
export const DELETE_SPITALI="DELETE_SPITALI";


export const GET_REPARTS ="GET_REPARTS";
export const GET_REPARTI="GET_REPARTI";
export const CREATE_REPARTI="CREATE_REPARTI";
export const DELETE_REPARTI="DELETE_SPITALI";


export const GET_MJEKETS ="GET_MJEKETS";
export const GET_MJEKET="GET_MJEKETS";
export const CREATE_MJEKET="CREATE_MJEKETS";
export const DELETE_MJEKET="DELETE_MJEKETS";

export const GET_TAKIMETS ="GET_TAKIMETS";
export const GET_TAKIMET="GET_TAKIMET";
export const CREATE_TAKIMET="CREATE_TAKIMET";
export const DELETE_TAKIMET="DELETE_TAKIMET";

export const GET_PACINETS ="GET_PACINETS";
export const GET_PACINETI="GET_PACINETI";
export const CREATE_PACINETI="CREATE_PACINETI";
export const DELETE_PACIENTI="DELETE_PACIENTI";

export const GET_INFERMIERETS ="GET_PACINETS";
export const GET_INFERMIERI="GET_PACINETI";
export const CREATE_INFERMIERI="CREATE_INFERMIERI";
export const DELETE_INFERMIERI="DELETE_INFERMIERI";

export const GET_ALERGJIAS ="GET_ALERGJIAS";
export const GET_ALERGJIA="GET_ALERGJIA";
export const CREATE_ALERGJIA="CREATE_ALERGJIA";
export const DELETE_ALERGJIA="DELETE_ALERGJIA";

export const GET_SPECIALIZIMETS ="GET_SPECIALIZIMETS";
export const GET_SPECIALIZIMET="GET_SPECIALIZIMET";
export const CREATE_SPECIALIZIMET="CREATE_SPECIALIZIMET";
export const UPDATE_SPECIALIZIMET="UPDATE_SPECIALIZIMET";
export const DELETE_SPECIALIZIMET="DELETE_SPECIALIZIMET";

export const GET_RECETA = "GET_RECETA";
export const GET_RECETAS = "GET_RECETAS";
export const CREATE_RECETA = "CREATE_RECETA";
export const UPDATE_RECETA = "UPDATE_RECETA";
export const DELETE_RECETA = "DELETE_RECETA";

export const CREATE_USER="CREATE_USER";
export const LOGIN_USER="LOGIN_USER";
export const LOGOUT_USER="LOGOUT_USER";

export const GET_USER="GET_USER";
export const GET_USERS="GET_USERS";
export const GET_TAKIMBYID="GET_TAKIMBYID";

